os: linux
dist: focal
arch: ppc64le

services:
    - docker
    
before_install:
    - sudo apt install -y jq; jq --version
    # Currently pointing to test branch code of build-script repo
    - git clone https://github.com/nikhil-kalbande/build-scripts.git
    - cd build-scripts; git checkout jen-travis-mig


jobs:
  include:
    - stage: warm_cache
      script:
        - echo "Hello world" > foo.txt
      workspaces:
        create:
          name: ws1
          paths:
            - foo.txt
    - stage: use_cache
      workspaces:
        use: ws1
      git:
        clone: false
      script:
        - cat foo.txt
