os: linux
dist: focal
arch: ppc64le

services:
    - docker
    

jobs:
  include:
    - stage: warm_cache
      before_install:
        - sudo apt install -y jq; jq --version
        # Currently pointing to test branch code of build-script repo
        - git clone https://github.com/nikhil-kalbande/build-scripts.git
        - cd build-scripts; git checkout jen-travis-mig; cd d/d3-color
      script:
        - ls -ltr
        - pwd
      workspaces:
        create:
          name: ws1
          paths:
            - .
    - stage: use_cache
      workspaces:
        use: ws1
      before_script:
        - ls -ltr
        - pwd
        - cd /home/travis/build/saiNammi/nsp/build-scripts/d/d3-color
        - ls -ltr
      script:
        - ls -ltr
        - pwd
