os: linux
dist: focal
arch: ppc64le

services:
    - docker

jobs:
  include:
    - stage: warm_cache
      script:
        - echo "Hello world" > foo.txt
      workspaces:
        create:
          name: ws1
          paths:
            - foo.txt
    - stage: use_cache
      workspaces:
        use: ws1
      script:
        - cat foo.txt
