os: linux
dist: focal
arch: ppc64le

services:
    - docker

jobs:
  include:
    - stage: warm_cache
      before_script:
        - sudo apt install -y jq; jq --version
        - git clone https://github.com/nikhil-kalbande/build-scripts.git
        - cd build-scripts; git checkout jen-travis-mig
      script:
        - echo "Hello world" > foo.txt
      workspaces:
        create:
          name: ws1
          paths:
            - foo.txt
    - stage: use_cache
      workspaces:
        use: ws1
      script:
        - cat foo.txt
