name: test_script
on:
  schedule:
    - cron: "*/5 * * * *"
  
  workflow_dispatch:

jobs:
  example-job:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          
      - name: date
        shell: bash
        run: |
          date >> ./date.log
      
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: date.log
          commit-msg: Update resources
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run build script
        run: |
          chmod 777 ./.github/scripts/build.sh
          ./.github/scripts/build.sh
        shell: bash
