name: test_script
on:
  schedule:
    - cron: "*/5 * * * *"
  
  workflow_dispatch:
  
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: update date
        shell: bash
        run: |
          date >> ./date.log
  
      - name: Run build script
        run: |
          chmod 777 ./.github/scripts/build.sh
          ./.github/scripts/build.sh
        shell: bash
