name: test_script
on:
  schedule:
    - cron: "*/5 * * * *"
  
  workflow_dispatch:
  
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v3
        with:
          name: homework
          path: math-homework.txt
          
      - name: date
        shell: bash
        run: |
          date >> ./date.log
      
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: updatedDate
          path: date.log
          
      - name: Run build script
        run: |
          chmod 777 ./.github/scripts/build.sh
          ./.github/scripts/build.sh
        shell: bash
